import "~/styles/globals.css";

import {Inter} from "next/font/google";

import {TRPCReactProvider} from "~/trpc/react";
import {SideNav} from "~/app/components/SideNav";
import {NextAuthProvider} from "~/app/components/NextAuthProvider";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Jobs App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children,}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
        <div className="container mx-auto flex items-start">
            <NextAuthProvider>
                <SideNav/>
                <div className="min-h-screen flex-grow border-x sm:pr-4">
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </div>
            </NextAuthProvider>


        </div>

        </body>
        </html>
    );
}
